### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by CTB33391** [SmashingMods/Alchemistry#13]
- Fume Collector: this would be a block that - when placed over fire or an active furnace - would collect and output carbon dioxide.
- Psilocybin could be made into a 'psychoactive potion' that inflicts nausea.
- A machine that combines things with an element. For example, 'galvanising' steel or iron by applying zinc in case a mod uses galvanised metal.
- Batteries that can store RF/FE, EU, Tesla etc. These would be made by filling a craftable battery case with lithium at the aformentioned machine.
- Machines support energy-containing items, to go with above.
- Thermite, made with any powdered metal and metal oxide. Stronger than TNT and ignites all entities in the blast radius.
- Decomposing cactus.

**Comment by al132mc** [comment]
I added a cactus recipe a few versions ago. The other ideas are interesting and i'm not inherently opposed to any of them, but I don't plan on adding them in the near future. I will keep this issue open, however.

**Comment by al132mc** [comment]
Psilocybin is now "psychoactive" though I hate nausea, so it doesn't use the nausea effect

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
