### ISSUE TITLE
Suggestion: Portable Dissolver

### ISSUE THREAD

**Issue by pip69** [SmashingMods/Alchemistry#28]
The title gives the concept, here's some ways it could work:

  - Includes a scanner function to see what elements you could get from a block, maybe similar to how Thaumcraft does it.
  - The speed to dissolve a block would be based on the # of elements.  Would not work if block has no elements.   
  -  Either part the item or as a separate item, some kind of storage for elements,  It could hold a large amount of elements, but only a few different types.
  -  RF powered, but could also use any burnable element as fuel
  -  Have a way to "search" for a specific element.  Gives that block a Glow effect if in range.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
