### ISSUE TITLE
[Suggestion] Drugs and Medicine

### ISSUE THREAD

**Issue by cybercat5555** [SmashingMods/Alchemistry#34]
Alchemistry already has elements of this in the form of mescaline and psilocybin, but why not take it a step farther? Drugs and medicines were a large part of Minechem, as well as lacing both food and tools with them, both for fun and for function.

For a few more examples:
Penicillin: C16H18N2O4S, cures all negative effects from a player, as well as a minor bit of regeneration
Aspirin: C9H8O4, insta restores some health, provides a bit of regen and absorption
Mescaline: Night vision, and perhaps a new effect where it causes "fake" mobs to spawn near the player (only visible to them), some look realistic, others are tinted colours (similar to the old Psychedelicraft mod)
Psilocybin: All mobs are given the "glowing" effect that only the person affected by the chemical can see. Chance of nausea and nightvision as well, as well as the hallucinogenic mobs from above.
Adrenaline: C9H13NO3, gives the player a large speed, damage, and resistance boost, but also inflicts hunger on them afterwards.
Potassium Cyanide: already in the mod, should insta-kill those who consume it or are otherwise exposed to it after several seconds, possibly with a way to bypass other mods that let the player ignore statue effects

To avoid making this already bigger than it is, I'll stop here, but I can always add on to this list later.

**Comment by al132mc** [comment]
I have added all of these except for Mescaline in v1.0.3, with effects similar to what you've suggested. I will leave this issue open for now though

**Comment by cybercat5555** [comment]
Thought up a few more chemicals:
Methamphetamine: C10H15N, High speed and resistance, but inflicts damage when used
LSD: C20H25N3O, Night vision, other mobs get affected with glowing (only you see it), and minor nausea, but also generates fake mobs and plays fake sounds (both of mobs and the Super Secret Settings sounds). 
Ergotamine: C33H35N5O5, obtained from decomposing wheat and similar grains, precursor to LSD. Inflicts weakness but nightvision as well on the user
THC: C21H30O2, Regen and absorption, but a bit of slowness, minor nausea, and hunger. Change of getting it from decomposing hemp crops from other mods (i.e. fiberHemp  and things like Immersive Engineering's hemp seeds)
Thaimine: C12H17N4OS, Fills a few food bars as well as gives saturation, chance of getting it from decomposing meats as well as Tall Grass and Double Tall Grass
Barbituric acid: C4H4N2O3, extreme slowness, blindness, and mining fatigue, good for adding to weapons in PvP
Lidocaine: C14H22N2O, absorbition and minor regen
Sulfuric Acid: H2SO4, inflicts massive damage, poison, and blindness. Also good for PvE and PvP. Sulfuric acid is also used in some other mods iirc, so a way to use the liquidfier to make it into the fluid block would be good too
Ethanol: already in, but should have a liquidfier recpie to make ethanol fluid for other mods (such as Immersive Engineering)

**Comment by al132mc** [comment]
Spiking food added in 1.0.4, more of these suggestions to come in future versions i'm sure..

**Comment by Chalky123b** [comment]
Another suggested chemical is Cholecystokinin, has a molecular formula of C166 H261 N51 O52 S4.
How you're going to get it created is beyond me (probably with a combination of chemicals, like CO, NO, H20 etc.

The idea is that cholecystokinin is a food that makes you feel full (gives saturation), so it nedded to be complex enough that it isnt easy to make.

**Comment by pip69** [comment]
There should a config option to disable either this alone or all drugs

New status affect: Addiction & Withdrawal
   When any of the above is consumed, there is a chance for this status affect to be added.  If this is active then when any of the above is consumed time is added to this status.  Maybe time is 2x the duration from when a Drug is consumed. 
   There are no affects while this is active.  When Addiction ends, you get Withdrawal.  Withdrawal has duration equal to highest duration of Addiction.    Gives a bunch of negative status affects for the duration of Withdrawal.  Maybe random affects, that change every minute?

If able to, maybe a config option to have potions be counted towards Addiction.

**Comment by xyberviri** [comment]
Is it possible to exposed the functionality to turn compounds into what ever object type it is that is consumable by the player?

I havent dug into mc code in a while but if it was possible add a new compound and then say call newcompound.addStatusEffect(int StatusEffect,int duration)
and just map the status effects from https://minecraft.gamepedia.com/Status_effect
to the compound and boom. 

you can let others add effects to what ever compounds they add.

**Comment by Lancelot3452** [comment]
> Thought up a few more chemicals:
> Methamphetamine: C10H15N, High speed and resistance, but inflicts damage when used
> LSD: C20H25N3O, Night vision, other mobs get affected with glowing (only you see it), and minor nausea, but also generates fake mobs and plays fake sounds (both of mobs and the Super Secret Settings sounds).
> Ergotamine: C33H35N5O5, obtained from decomposing wheat and similar grains, precursor to LSD. Inflicts weakness but nightvision as well on the user
> THC: C21H30O2, Regen and absorption, but a bit of slowness, minor nausea, and hunger. Change of getting it from decomposing hemp crops from other mods (i.e. fiberHemp and things like Immersive Engineering's hemp seeds)
> Thaimine: C12H17N4OS, Fills a few food bars as well as gives saturation, chance of getting it from decomposing meats as well as Tall Grass and Double Tall Grass
> Barbituric acid: C4H4N2O3, extreme slowness, blindness, and mining fatigue, good for adding to weapons in PvP
> Lidocaine: C14H22N2O, absorbition and minor regen
> Sulfuric Acid: H2SO4, inflicts massive damage, poison, and blindness. Also good for PvE and PvP. Sulfuric acid is also used in some other mods iirc, so a way to use the liquidfier to make it into the fluid block would be good too
> Ethanol: already in, but should have a liquidfier recpie to make ethanol fluid for other mods (such as Immersive Engineering)
> Polyvinyl Chloride: Can also create itemPlastic used in other mods

Well then, here are some other drugs to add:
MDMA: causes euphoria, some sort of desire to cuddle
2CB: hallucinogenic aphrodisiac
Fluoxetine (prozac): anti-depressant, causes hallucinations and aggression with overdosing
Amphetamine: temporarily gives speed and haste, after wearing off you get the downsides

**Comment by xyberviri** [comment]
Eh, more drugs and what not aren't really needed cause it will turn this into a drugs mod.

All that's needed is an option to flip a compound to have the "isfood" nbt tag, then also be able to add potion effect tags, the healing and saturation amount.

With that you could make a compound that makes you go blind when you eat it. 

But nbt tags I'm learning are pretty nasty and can cause those too bug packets error

**Comment by Lancelot3452** [comment]
Actually, we shouldn't give too much drugs to this mod. This also might include adding more effects, like hallucination. At the same time, it actually could be fun having multiple types of drugs. For this, you can add two edible polymers: HPMC and gelatin. With this, you can literally make pills

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
