### ISSUE TITLE
Advanced Combiner

### ISSUE THREAD

**Issue by pip69** [SmashingMods/Alchemistry#37]
The basic concept;  
- multiple slots that can be set for different recipes
- if components are used for more than 1 recipe, can be set to balance or priority
- able to preset quantity to make, won't accept components make excess of this

A possible way it could be implemented;
- free form multiblock.  every block is the same, more just expand on the capabilities
- initial processing speed slower than the normal combiner, any slot not actively combining speeds up the others
- internal storage (both input & output) increases with more blocks. 
- maybe have the speed tied to RF use,  each block able use #rf per tick, so the RF could be split among all the recipes or focused on 1.

**Comment by daan7008** [comment]
maybe something inspired by Blood magic runes. Some block gives like more processing speed and an other one gives efficiency or something like that.

**Comment by pip69** [comment]
Or like Advanced Generators.  All depends on if you want fixed structures or free form ones.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
