### ISSUE TITLE
Expanding the Wet Sand concept

### ISSUE THREAD

**Issue by pip69** [SmashingMods/Alchemistry#43]
Wet Farmland
Fertilized Farmland
Fertilized Dirt (for trees)

Maybe being able to set a duration or # of uses before changing back to normal
Have an in world transformation method

**Comment by daan7008** [comment]
its a good idea but isnt there alot of options for this out there already?

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
