### ISSUE TITLE
Allow us to place liquid forms of elements directly

### ISSUE THREAD

**Issue by AceSevenFive** [SmashingMods/Alchemistry#44]
In MineChem, you could place the liquid form of elements that have one by right clicking it on a block with (I believe) 16 of it. Adding that feature would allow for some interesting creations (cyanide moats, for example.)

**Comment by al132mc** [comment]
Sorry for not responding earlier. I have no plans to implement this feature. Accidentally placing down fluids was my least favorite thing about minechem. I will keep this issue open just in case, though.

**Comment by MasterEnderman** [comment]
https://github.com/SmashingMods/Alchemistry/issues/138
