### ISSUE TITLE
Allow us to enable a recursive option for recipe gathering

### ISSUE THREAD

**Issue by AceSevenFive** [SmashingMods/Alchemistry#50]
In MineChem, there was a config option allowing the mod to recursively gather recipes based on what items are available; having that in Alchemistry would be very cool. (Though, given that mods are a bit more complicated than in 1.7.10, perhaps it would be better for the option to be off by default.)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
