### ISSUE TITLE
Power generation

### ISSUE THREAD

**Issue by daan7008** [SmashingMods/Alchemistry#54]
It would be cool to have Power generator within the alchemistry mod so it could be played without any other mods. Some ideas i have on this suggestion:
It should be 2 multiblocks one for midgame and one for early game, cost to make machines should be according to the progression.  You could make a basic reactor and a advanced reactor.

Next idea is that the reactor runs on fluids from elements. So the liquifier has more uses. 

The reactor will work on a Fuel element and a coolant element. Like the reactant dynamo of TE but in a multiblock structure

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
