### ISSUE TITLE
Multiblock World Visualisation is 2 layers in the ground...

### ISSUE THREAD

**Issue by Fireztonez** [SmashingMods/Alchemistry#55]
Hello, 

### Introduction
I just installed Alchemistry and I am really pleasantly surprised at everything that has been done since the moment I tried it for the first time, maybe 6 months ago. All the multi-blocks, and the new machines, it's extra ordinary!
I really think your mod has a huge potential, so keep up the great work !!

### Problem
I look the book question to see how to build the Multiblock structure, I click question to visualize how to build the structure and shift + Right-Click on the floor, question to anchor the preview, the Visualisation is 2 blocks in the ground, like you can see in this picture:
![fission-multiblock-visual-glitch](https://user-images.githubusercontent.com/19277301/58753839-7769eb80-8493-11e9-8445-35e1056200c8.jpg)

I do not know if it is currently possible, with Patchouli to change the way the survey is placed in the world. Question of always placing the preview on the block you are looking at (if you look at the ground), but I think it should be nice! because now, I have to place a pile of 2 block on the ground, question to lock the preview at the good level.

Other things, and again, I don't know if this is possible or not with Patchouli, but having a possibility to see the build level by level in book should be really cool, because now this is just impossible to see the inside in the book and possibly when you build show only one layer at the time should be easier to see how to place each blocks (Like when you build a structure with the  Immersive Petroleum Projector)
![image](https://user-images.githubusercontent.com/19277301/58754104-c1ed6700-8497-11e9-9cea-fafd27aa871c.png)

If this is not possible currently with Patchouli, this can be cool to see if it can add this possibilities, because I think this can be usefull for a lot of mod!!

And, a little detail possibly, but, I think you should change the book icon, because I have now 2 different mods having the exact same book icon (This is probably the default one from Patchouli!?)... Making one with an Erlenmeyer flask or something like that should be nice I think ;)

### Version:
Forge: 14.23.5.2838
Alchemistry: 1.0.20
Patchouli: 1.0-19

Thank's
Fireztonez

**Comment by al132mc** [comment]
1. Awesome :) Glad you're liking the mod
2. The in-world positioning shouldn't be hard to fix, a fix should be out within a few days
3. I don't believe there is any way to have layer-by-layer view for the multiblock, that's completely within the realm of patchouli devs. Fortunately, the design of the multiblocks is quite simple.
4. I'll see what I can do with the book logo

**Comment by Fireztonez** [comment]
Super thank's al132mc!

Yes the design is pretty simple, but little hard to see what goes where because you always see one block on another one in the preview, but, I know this is not your fault if patchouli doesn't support layer pby layer now...

Other thing, the 3D preview in the book is wrong, the way how face the controller blocks doesn't work... The controller block should be turn by 90 degrees, unless it doesn't work... ;)

**Comment by al132mc** [comment]
In v1.0.22 i've fixed the visualizations being 2 blocks down. I'll leave this issue open for the other minor issues, however.

**Comment by phatnynja** [comment]
This is the closest thing I could find to my issue. I accidently placed the template in chemical exchange and it's pretty annoying as not alot of room and being I just started an nowhere near building this how do I get rid of the template?

**Comment by skiller8641** [comment]
normally you just right click somewhere else or go in the book and press the button again, no?

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
