### ISSUE TITLE
UV light+circuits

### ISSUE THREAD

**Issue by daan7008** [SmashingMods/Alchemistry#56]
Just like in the old Pneumaticcraft you could use UV light to make circuits. Those circuits could be used to make other Alchemistry machines like the dissolver.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
