### ISSUE TITLE
[1.12.2] Broken Autocrafting with Combiner using Refined Storage

### ISSUE THREAD

**Issue by MasterEnderman** [SmashingMods/Alchemistry#57]
Even if you define the recipe in the right order and place the pattern in a crafter facing a combiner without a locked recipe the recipes are imported in the wrong order.
This is caused by something that changed in the last updates, because i tested it before and it worked back then.

**Comment by al132mc** [comment]
Could you provide some screenshots please?

**Comment by MasterEnderman** [comment]
The Crafting Pattern: 
![image](https://user-images.githubusercontent.com/24524662/59072656-b351e600-88c3-11e9-9d9b-f236456359b6.png)
How the Crafter puts it in the machine: 
![image](https://user-images.githubusercontent.com/24524662/59072691-dd0b0d00-88c3-11e9-9b06-6fbb2e662911.png)

**Comment by al132mc** [comment]
We chatted and this is likely an RS issue because even when using a pattern with iron swords instead of slot fillers and even when inserting into a chest instead of a combiner it still puts them in the wrong order.

**Comment by StewartNZ** [comment]
Been having the same problem, was wondering if it was at all possible to make slot fillers filling the combiner from the last slot.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
