### ISSUE TITLE
Deuterium/Heavy Water?

### ISSUE THREAD

**Issue by ghost** [SmashingMods/Alchemistry#64]
![Untitled](https://user-images.githubusercontent.com/39097092/59697373-51db2280-91b3-11e9-8a4a-e4eb00fd7dbb.png)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
