### ISSUE TITLE
Gems dissolver and combine

### ISSUE THREAD

**Issue by kotelkonrad** [SmashingMods/Alchemistry#65]
dissolver and combine gems for another mods (silent gems)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
