### ISSUE TITLE
NuclearCraft Integration? 

### ISSUE THREAD

**Issue by ghost** [SmashingMods/Alchemistry#69]
[NuclearCraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod) is a mod about nuclear science. Your mod and NuclearCraft has a lot of elements in common, such as Californium, Berkelium and Curium. However, these elements in each mod is not convertible to each other. Is it able to make them convertible. Please improve the interaction with NuclearCraft, thanks.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
