### ISSUE TITLE
Patcholi displays Fission/Fussion controller rotated 90 counter clockwise.

### ISSUE THREAD

**Issue by xyberviri** [SmashingMods/Alchemistry#78]
![javaw_2019-07-18_20-46-29](https://user-images.githubusercontent.com/1403624/61502023-0c6f6800-a9a0-11e9-8255-a74626be7270.png)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
