### ISSUE TITLE
[Suggestion] polymers, some fluids and integration with IE (Immersive Engineering)

### ISSUE THREAD

**Issue by Lancelot3452** [SmashingMods/Alchemistry#80]
My suggestion to this mod is a part where I've been involved IRL, polymerization of substances.
Examples:
R* (radical) + styrene -> polystyrene
![image](https://user-images.githubusercontent.com/53128998/61585058-79772f00-ab53-11e9-8b23-3016d934154d.png)

Bisphenol A + phosgene -> polycarbonate (strong polymer, used in riot gear)
![image](https://user-images.githubusercontent.com/53128998/61585057-72e8b780-ab53-11e9-9588-dcaf5989ffa8.png)

Decane diacid + hexane-1,6-diamine -> nylon 6,10 (used to make pantyhose)
![image](https://user-images.githubusercontent.com/53128998/61585055-65cbc880-ab53-11e9-915d-04446b2ee902.png)

Paraphenylamine + terephthalate acid -> polyaramide (kevlar)
![image](https://user-images.githubusercontent.com/53128998/61585042-19808880-ab53-11e9-9dcb-7bf05f18ec71.png)
R* + ethene -> polyethylene (used in plastic bags)
![image](https://user-images.githubusercontent.com/53128998/61585088-eab6e200-ab53-11e9-80cd-36d60a1c607c.png)

R* + propene -> polypropylene (resistant to sulfuric acid)
![image](https://user-images.githubusercontent.com/53128998/61585091-facec180-ab53-11e9-9e75-b62da6bd689f.png)

![image](https://user-images.githubusercontent.com/53128998/61585044-2604e100-ab53-11e9-96cc-001cc1931afd.png)

R* + chloroethene -> PVC
![image](https://user-images.githubusercontent.com/53128998/61585066-8ac03b80-ab53-11e9-84a1-fad966eb08bb.png)

R* + tetrafluoroethene -> PTFE (teflon) (can survive temparatures above 4000 degrees Celsius and is resistant to fluor antimonic acid)
![image](https://user-images.githubusercontent.com/53128998/61585038-0ff72080-ab53-11e9-9a45-6ebeb1391d0b.png)

Carbon gas (in specific heating unit) > carbon nanotubes (good conductor of electricity, some types are less conductive)
![image](https://user-images.githubusercontent.com/53128998/61585071-a0cdfc00-ab53-11e9-87d4-029770abc202.png)

Aside from the polymers, we can expect to add in the ingredients for the polymers themselves and maybe add a polymerizer as functional block.

Calcium fluoride for the synthesis of HF (hydrofluoric) acid, so also add HF
And some antimonepentafluoride, which forms fluoroantimonic acid when it reacts with HF

important property about fluoroantimonic acid: dissolves everything except teflon.

Aqua Regia: contains for each molecule HNO3 (nitric acid) three molecules HCl (hydrochloric acid). Dissolves gold

And lastly the one specific integration with immersive engineering: fluids can be used for chemical thrower. (Imagine spraying acid on mobs)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
